2017-05-29 03:03:20.083 - info: service : /mongo/api/v1/client
2017-05-29 03:03:20.088 - info: service : /mongo/api/v1/client
2017-05-29 03:03:20.100 - info: escuchando  : 0.0.0.0:5002
2017-05-29 03:03:22.132 - error: uncaughtException: connection 0 to localhost:27017 timed out date=Mon May 29 2017 03:03:22 GMT-0500 (Hora est. Pacífico, Sudamérica), pid=41748, uid=null, gid=null, cwd=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate, execPath=D:\nodejs-6.9.4\node.exe, version=v6.9.4, argv=[D:\nodejs-6.9.4\node.exe, E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\server.js], rss=50888704, heapTotal=35688448, heapUsed=23617288, loadavg=[0, 0, 0], uptime=220092.6320238, trace=[column=11, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\error.js, function=Function.MongoError.create, line=29, method=create, native=false, column=20, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=188, method=null, native=false, column=16, file=events.js, function=Socket.g, line=291, method=g, native=false, column=13, file=events.js, function=emitNone, line=86, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=185, method=emit, native=false, column=8, file=net.js, function=Socket._onTimeout, line=339, method=_onTimeout, native=false, column=14, file=timers.js, function=ontimeout, line=365, method=null, native=false, column=5, file=timers.js, function=tryOnTimeout, line=237, method=null, native=false, column=5, file=timers.js, function=Timer.listOnTimeout, line=207, method=listOnTimeout, native=false], stack=[MongoError: connection 0 to localhost:27017 timed out,     at Function.MongoError.create (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\error.js:29:11),     at Socket.<anonymous> (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\connection.js:188:20),     at Socket.g (events.js:291:16),     at emitNone (events.js:86:13),     at Socket.emit (events.js:185:7),     at Socket._onTimeout (net.js:339:8),     at ontimeout (timers.js:365:14),     at tryOnTimeout (timers.js:237:5),     at Timer.listOnTimeout (timers.js:207:5)]
2017-05-29 05:09:53.888 - info: service : /mongo/api/v1/client
2017-05-29 05:09:53.892 - info: service : /mongo/api/v1/client
2017-05-29 05:09:53.903 - info: escuchando  : 0.0.0.0:5002
2017-05-29 05:18:07.892 - info: service : /mongo/api/v1/client
2017-05-29 05:18:07.895 - info: service : /mongo/api/v1/client
2017-05-29 05:18:07.907 - info: escuchando  : 0.0.0.0:5002
2017-05-29 05:18:26.012 - info: service : /mongo/api/v1/client
2017-05-29 05:18:26.016 - info: service : /mongo/api/v1/client
2017-05-29 05:18:26.028 - info: escuchando  : 0.0.0.0:5002
2017-05-29 05:18:29.098 - error: error al registrar el documento
2017-05-29 05:18:29.098 - error:  ValidationError: Client validation failed: identity: Cast to Number failed for value "asdf1" at path "identity"
    at MongooseError.ValidationError (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongoose\lib\error\validation.js:26:11)
    at model.Document.invalidate (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongoose\lib\document.js:1594:32)
    at model.Document.set (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongoose\lib\document.js:753:10)
    at model._handleIndex (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongoose\lib\document.js:587:14)
    at model.Document.set (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongoose\lib\document.js:547:24)
    at model.Document (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongoose\lib\document.js:71:12)
    at model.Model (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongoose\lib\model.js:46:12)
    at new model (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongoose\lib\model.js:3613:13)
    at IncomingMessage.model [as Client] (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongoose\lib\model.js:3611:16)
    at E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\services\client.js:33:22
    at Layer.handle [as handle_request] (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\express\lib\router\layer.js:95:5)
    at E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\express\lib\router\index.js:335:12)
2017-05-29 05:18:29.112 - error: uncaughtException: res.status is not a function date=Mon May 29 2017 05:18:29 GMT-0500 (Hora est. Pacífico, Sudamérica), pid=9332, uid=null, gid=null, cwd=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate, execPath=D:\nodejs-6.9.4\node.exe, version=v6.9.4, argv=[D:\nodejs-6.9.4\node.exe, E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\server.js], rss=53268480, heapTotal=38834176, heapUsed=25551200, loadavg=[0, 0, 0], uptime=228199.6135859, trace=[column=9, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\helpers\utils.js, function=Object.module.exports.sendError, line=27, method=sendError, native=false, column=26, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\services\client.js, function=null, line=36, method=null, native=false, column=16, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongoose\lib\model.js, function=null, line=3747, method=null, native=false, column=17, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongoose\lib\services\model\applyHooks.js, function=null, line=153, method=null, native=false, column=7, file=internal/process/next_tick.js, function=_combinedTickCallback, line=67, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=98, method=_tickCallback, native=false], stack=[TypeError: res.status is not a function,     at Object.module.exports.sendError (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\helpers\utils.js:27:9),     at E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\services\client.js:36:26,     at E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongoose\lib\model.js:3747:16,     at E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongoose\lib\services\model\applyHooks.js:153:17,     at _combinedTickCallback (internal/process/next_tick.js:67:7),     at process._tickCallback (internal/process/next_tick.js:98:9)]
